# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 07:38
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='user_profile', verbose_name='profile'),
        ),
    ]
