# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 05:06
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_img',
            field=versatileimagefield.fields.VersatileImageField(default=None, upload_to='user_profile', verbose_name='profile'),
        ),
    ]
