branch-defaults:
  eb:
    environment: team2-dev
    group_suffix: null
  yusung:
    environment: team2-dev
global:
  application_name: team2
  branch: null
  default_ec2_keyname: team1-wps
  default_platform: Python 3.4
  default_region: ap-northeast-2
  profile: eb-cli
  repository: null
  sc: git
