# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='photo', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectTodayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Today3photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='today', verbose_name='image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('is_good', models.BooleanField(default=False)),
                ('is_bad', models.BooleanField(default=False)),
                ('is_not_know', models.BooleanField(default=False)),
                ('select_count', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_set_author', to=settings.AUTH_USER_MODEL)),
                ('select_users', models.ManyToManyField(related_name='photo_set_select_users', through='post.SelectTodayPhoto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='today3photo',
            name='photo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='post.TodayPhoto'),
        ),
        migrations.AddField(
            model_name='today3photo',
            name='photo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad', to='post.TodayPhoto'),
        ),
        migrations.AddField(
            model_name='today3photo',
            name='photo3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know', to='post.TodayPhoto'),
        ),
        migrations.AddField(
            model_name='selecttodayphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.TodayPhoto'),
        ),
        migrations.AddField(
            model_name='selecttodayphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
